### ISSUE TITLE
Make fourmolu version an input

### ISSUE THREAD

**Issue by brandonchinn178** [haskell-actions/run-fourmolu#17]
I don't see any reason the version can't be an input. It would allow the version of the action to be decoupled from the version of fourmolu, which has multiple benefits:
* Avoid maintenance burden of making release for every Fourmolu release
* Reading a github action clearly shows what version of Fourmolu is being used (and makes it easy to update)

**Comment by cdepillabout** [comment]
That makes sense!

When I originally copied `fourmolu-action` from `ormolu-action`, the version that was being used was hard-coded:

https://github.com/mrkkrp/ormolu-action/blob/4b9de76efeefdf7b0791bec94588d076d917ec64/index.js#L9

But it looks like that restriction has been lifted in recent versions (like the current `master`):

https://github.com/mrkkrp/ormolu-action/blob/eb399a5c4be9c7924076509bc4640965ab2827a4/index.js#L9

We should probably copy over this updated version logic as well.

**Comment by cdepillabout** [comment]
Here's the commit that made the above change in the `run-ormolu` action:

https://github.com/haskell-actions/run-ormolu/commit/2bf84706f6465a4ef89b503291e9cbe31032190e

Although, ideally, when you pass `"latest"` as the version, the Action should dynamically look up the Fourmolu releases, and pick the latest one (rather than having it hard-coded in the `index.js` file).
